---
dependencies:
  - role: firewall
    tags: [firewall, iptables, nftables]
  - role: consul
    tags: [consul]
  - role: nginx
    tags: nginx
    vars:
      php: yes
  - role: consul-template
    tags: consul-template