---
  - import_tasks: packages.yml
    tags:
      - mirrorbits
      - rsync

  - import_tasks: nftables.yml
    tags:
      - firewall

  - import_tasks: sanity.yml
    tags: users

  - import_tasks: rsync-server.yml
    tags: rsync

  - import_tasks: mirrorbits.yml
    tags: mirrorbits

  - import_tasks: uploaders.yml
    tags:
      - users
      - uploaders

  - import_tasks: cdn-app.yml
    tags:
      - users
      - cdn-app

  - import_tasks: static.yml
    tags: static

  - import_tasks: nginx.yml
    tags:
      - nginx
