---
  - name: install default packages
    apt: name={{ packages|flatten(levels=1) }} state=latest update_cache=yes
    tags: packages
    vars:
      packages:
      - mirrorbits #voc package
      - mirrorbits-serverlist-api #voc package
      - rsync
      - redis-server
