---
- copy: src={{ item }}
        dest=/usr/local/bin
        owner=root group=root mode=0755
  with_items:
    - mkindex.sh
    - mkindex_local.sh

- cron: user=root minute="13" cron_file="local_mkindex"
        job="if [ -x /usr/local/bin/mkindex.sh ]; then /usr/local/bin/mkindex.sh; fi;"
        name="update mkindex"

- cron: user=root minute="30" cron_file="local_mkindex"
        job="if [ -x /usr/local/bin/mkindex_local.sh ]; then /usr/local/bin/mkindex_local.sh; fi;"
        name="update mkindex local"

- template: src=rsyncd.conf
            dest=/etc/rsyncd.conf
            mode=0644 owner=root group=root

- name: enable rsyncd
  lineinfile: dest=/etc/default/rsync
              regexp='^RSYNC_ENABLE.*' state=present
              line="RSYNC_ENABLE=true"

- name: write rsyncd.secrets
  copy: dest=/etc/rsyncd.secrets
      content={{ rsync_secrets }}
      mode=0640 owner=root group=root

- name: write rsyncd-congress.secrets
  copy: dest=/etc/rsyncd-congress.secrets
      content={{ rsync_secrets_public }}
      mode=0640 owner=root group=root

- name: start and enable rsync service
  systemd:
    name: rsync.service
    state: started
    enabled: yes
