---
- name: add uploaders sftp to ssh config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match group uploaders
        ChrootDirectory %h
        X11Forwarding no
        AllowTcpForwarding no
        ForceCommand internal-sftp

# the user accounts
- group: name="uploaders" state=present
- file:
    dest: /home/uploaders
    state: directory

- user: state=present
        name="{{ item.name }}"
        group="uploaders"
        shell="/bin/false"
        home="/home/uploaders/{{ item.name }}"
        skeleton=false
        create_home=yes
  loop: "{{ uploaders }}"
  when: (item | dict2items | first).key not in hostvars[inventory_hostname].users
  tags: ['user']

- authorized_key:
    user: "{{ item.name }}"
    state: present
    key: '{{ item.keydata }}'
    key_options: "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty"
  loop: "{{ uploaders }}"

- name: bind mount uploader
  mount:
    path: "/home/uploaders/{{ item.name }}/ftp"
    src: /srv/ftp
    opts: bind,nofail,x-system.after=zfs-mount.service
    state: mounted
    fstype: none
  loop: "{{ uploaders }}"

- name: change uploaders home folder owner
  file:
    path: "/home/uploaders/{{ item.name }}"
    owner: root
    group: root
    mode: '0755'
  loop: "{{ uploaders }}"
