---
- name: add hashicorp apt key
  ansible.builtin.apt_key:
    id: 798AEC654E5C15428C8E42EEAA16FCBCA621E701
    url:  https://apt.releases.hashicorp.com/gpg
    state: present

- name: add hashicorp apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  register: consul_repo

- name: install consul
  apt:
    name: consul
    state: latest
    update_cache: yes
  when: consul_repo.changed
  register: consul_pkg

- name: deploy consul config
  template:
    src: consul.hcl
    dest: /etc/consul.d/consul.hcl
    mode: 0640
    owner: consul
    validate: "/usr/bin/consul validate -config-format=hcl %s"
  register: consul_conf

- name: deploy consul firewall config
  template:
    src: consul.nft
    dest: /etc/nftables/consul.nft
    mode: 0640
    validate: "/usr/sbin/nft -cf %s"
  tags: [iptables, nftables, firewall]
  notify: reload firewall

- name: deploy consul telegraf config
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.d/consul.conf
    mode: 0640
    group: telegraf
  tags: [monitoring, telegraf]
  notify: reload telegraf
  when: consul_server|bool

- name: remove consul telegraf config
  file:
    path: /etc/telegraf/telegraf.d/consul.conf
    state: absent
  tags: [monitoring, telegraf]
  notify: reload telegraf
  when: not consul_server|bool

- name: start/enable consul
  service:
    name: consul
    enabled: yes
    state: started

- name: reload consul
  service:
    name: consul
    state: reloaded
  when: consul_pkg.changed or consul_conf.changed
  tags: consul-config