---
dependencies:
  - role: nginx
    vars:
      # the relay config listens on http and https
      default_server: no
      # currently required for viewer counting
      anonymize_logs: no
      # we only log playlists to access log
      default_access_log: no
    tags: nginx
  - role: letsencrypt
    vars:
      domain: "{{ ansible_fqdn }}"
    tags: letsencrypt
  - role: icecast
    vars:
      # setup distribution icecast on masters
      icedist: stream_master

      # burst on connect for user facing icecsat
      icecast_burst_on_connect: "1"
    tags: icecast