---
 - include: kernel.yml
   when: "system.type == 'pc' and 'proxmox' not in group_names"
   tags: kernel
 - include: general.yml
 - include: packages.yml
 - include: artwork.yml
   tags: artwork
 - include: encodermode-voctomix.yml
   tags:
    - encodermode
    - voctomix
 - include: encodermode-voctomix2.yml
   tags:
    - encodermode
    - voctomix2
 - include: icedist.yml
   tags: icedist
 - include: nginx.yml
   tags: nginx
 - include: samba.yml
   tags: samba
 - include: rc.local.yml
   tags:
     - rclocal
     - iptables
     - encodermode
 - include: rsync.yml
   tags: rsync
