---
# revert to normal acpi shutdown handling for VMs
- name: reenable logind handling of acpi events
  replace:
    path: /etc/systemd/logind.conf
    regexp: '^Handle(PowerKey|SuspendKey|HibernateKey|LidSwitch)(.*)$'
    replace: '#Handle\1\2'
  register: logind_conf

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: logind_conf.changed

- name: Populate service facts
  service_facts:

- name: stop/disable acpid
  service:
    name: acpid
    state: stopped
    enabled: no
  when: '"acpid" in ansible_facts.services and ansible_facts.services["acpid"]["state"] == "running"'

- name: remove acpid
  apt:
    name: acpid
    state: absent