---
- name: install acpid
  apt:
    name: acpid
    state: latest

# Prevent pressing power button
- name: create script for custom power button sequence
  copy:
    src: powerbtn-acpi-support_voc.sh
    dest: /etc/acpi/powerbtn-acpi-support_voc.sh
    mode: 0755

- name: activate custom acpi script for power button
  lineinfile:
    dest: /etc/acpi/events/powerbtn-acpi-support
    regexp: '^action=.*'
    line: 'action=/etc/acpi/powerbtn-acpi-support_voc.sh'
  register: acpi_config

- name: restart acpid
  service:
    name: acpid
    state: restarted
  when: acpi_config.changed

- name: disable logind handling of acpi events
  replace:
    path: /etc/systemd/logind.conf
    regexp: '^#?Handle(PowerKey|SuspendKey|HibernateKey|LidSwitch).*$'
    replace: 'Handle\1=ignore'
  register: logind_conf

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: logind_conf.changed
