---
  - name: ensure grub is installed
    apt:
      name: grub-pc
      state: present

  # Grub config for real hardware
  - name: copy grub config for physical machines
    copy:
      src: grub/grub_default
      dest: /etc/default/grub
      mode: 0644
    when: ansible_virtualization_role != 'guest'
    register: grub_config

  # Grub config for virtual machines
  - name: copy grub config for virtual machines
    copy:
      src: grub/grub_default.vm
      dest: /etc/default/grub
      mode: 0644
    when: ansible_virtualization_role == 'guest'
    register: grub_config

  - name: update grub
    command: /usr/sbin/update-grub
    when: grub_config.changed
