---
  - name: deinstall ntpd
    apt: name=ntp state=absent

  # Setting timezone
  - shell: "{{ timedatectl_bin.stdout | default('timedatectl') }} status | grep 'Time zone' | cut -d ':' -f 2 | cut -d ' ' -f 2"
    register: current_timezone
    changed_when: false

  - name: setting timezone to Europe/Berlin
    command: "{{ timedatectl_bin.stdout | default('timedatectl' )}} set-timezone Europe/Berlin"
    when: current_timezone.stdout != "Europe/Berlin"

  # Timesyncd
  - shell: "{{ timedatectl_bin.stdout | default('timedatectl') }} status | grep -e 'NTP enabled\\|Network time on\\|NTP service: active' | cut -d ':' -f 2 | cut -d ' ' -f 2"
    register: ntp_enabled
    changed_when: false

  - name: enable systemd-timesyncd
    command: "{{ timedatectl_bin.stdout | default('timedatectl') }} set-ntp true"
    when: ntp_enabled.stdout != 'yes' and ntp_enabled.stdout != 'active'
