---
  - name: install a default set of packages
    apt: name={{ packages|flatten(levels=1) }} state=latest update_cache=yes
    tags: packages
    vars:
      packages:
      # YES, we are using systemd!!1!
      - systemd
      - systemd-sysv
      - zsh
      - vim
      - htop
      - iftop
      - tcpdump
      - ffmpeg
      - git
      - mtr-tiny
      - tmux
      - iperf
      - strace
      - iotop
      - screen
      - build-essential
      - bwm-ng
      - mosh
      - molly-guard
      - ncdu
      - debian-goodies
      - apt-dater-host
      - dnsutils
      - dstat
      - pv
      - buffer
      - lm-sensors
      - moreutils
      - python3
      - ruby
      - ruby-dev
      - libdbi1
      - libdbd-sqlite3
      - ethtool
      - ifenslave-2.6
      - apt-transport-https
      - irqbalance
      - mosquitto-clients
      - zip
      - unzip
      - bc
      - at

  # packages for physical hosts
  - name: install packages for physical hosts
    apt:
      name:
        - smartmontools
        - lldpd
      state: latest
    when: ansible_virtualization_role != 'guest'

  - name: add megacli
    apt: name=megacli state=present
    when: ansible_hostname is match('mebibyte')

  # packages for VMs
  - name: install a vmware specific set of packages
    apt: name=open-vm-tools state=present
    when: ansible_virtualization_type is defined and ansible_virtualization_type == 'VMware' and ansible_virtualization_role == 'guest'

  - name: install special packages for VMs
    apt: name=haveged state=present
    when: ansible_virtualization_type is defined and ansible_virtualization_role == 'guest'

  - name: install qemu-aguest-agent
    apt:
      name: qemu-guest-agent
      state: present
    when: ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'kvm'

  # remove not needed packages
  - name: remove not needed packages
    apt: name={{ packages|flatten(levels=1) }} state=absent
    vars:
      packages:
        - rpcbind
        - openntpd
        - rdnssd
        - dvswitch-voc
        - dvsource-voc
        - dvsink-voc
        - bmdtools
        - check-mk-agent
        - munin-node
        - puppet
    when: "'proxmox' not in group_names"
