---
 - name: remove pve enterprise list
   file:
     path: /etc/apt/sources.list.d/pve-enterprise.list
     state: absent

 - name: install packages needed for repos
   apt:
     name:
      - apt-transport-https
      - gpg
     state: latest
     update_cache: yes
   tags:
     - gpg

 # general
 - name: setup the VOC debian repo key
   apt_key: data="{{ lookup('file', 'voc_repo.key') }}" state=present
   tags:
     - repo
     - gpg
   when: "system.type == 'pc' and 'proxmox' not in group_names"

 #
 # remove old repos
 #

 - name: remove the VOC debian mng.ber repo before any updates are done since it is unavailable now pkg.c3voc is new
   apt_repository: repo="deb http://mng.ber.c3voc.de/debian/ {{ item }} main" state=absent
   when: system.type == 'pc'
   loop:
    - jessie
    - stretch
    - buster

 - name: remove yate nightly repo if present since it's key is not supported by stretch atm dsa1024 
   apt_repository: repo="deb http://debian.ctm.ru/nightly/ stable main non-free" state=absent

 # stretch specific
 - name: remove /etc/apt/sources.list
   file: dest=/etc/apt/sources.list state=absent

 - name: remove /etc/apt/sources.list.d/*
   file: dest=/etc/apt/sources.list.d/{{ item }} state=absent
   loop:
    - ftp_debian_org_debian.list
    - raspi.list

 #
 # add repos
 #

 - name: setup the debian backports repo for bullseye
   apt_repository: repo="deb http://ftp.de.debian.org/debian bullseye-backports main contrib non-free" update_cache=false
   when: system.type == 'pc'

 - name: ensure that the non-free suite is enabled for bullseye
   apt_repository: repo="deb http://ftp.de.debian.org/debian bullseye main contrib non-free" update_cache=false
   when: system.type == 'pc'

 - name: ensure that security updates enabled for bullseye
   apt_repository: repo="deb http://security.debian.org/ bullseye-security main contrib non-free" update_cache=false
   when: system.type == 'pc'

 - name: ensure that the debian keyrings are present
   apt: name={{ packages|flatten(levels=1) }} state=present update_cache=yes
   vars:
     packages:
      - debian-keyring
      - debian-archive-keyring
   when: system.type == 'pc'

 - name: setup the VOC debian repo for bullseye
   apt_repository: repo="deb http://pkg.c3voc.de/ bullseye main" state=present
   when: "system.type == 'pc' and 'proxmox' not in group_names"

#
# raspberry specific
#

 - name: setup the raspbian debian repo for bullseye
   apt_repository: repo="deb http://mirrordirector.raspbian.org/raspbian/ bullseye main contrib non-free rpi" state=present
   when: system.type == 'pi'

 - name: setup the raspbian debian repo for bullseye
   apt_repository: repo="deb http://archive.raspberrypi.org/debian/ bullseye main ui" state=present
   when: system.type == 'pi'

 - name: remove pinning for ffmpeg multimedia repo since it is now in the default repo
   file: dest=/etc/apt/preferences.d/apt-pin-ffmpeg-multimedia.pref state=absent
   when: system.type == 'pi'

#
# Configure pinning
#

 - name: pin the VOC repo to the highest priority
   copy: src=voc-repo-pinning
         dest="/etc/apt/preferences.d/voc.pref"
         mode=0644 owner=root group=root


#
# LSI RAID controller specific
#
 - name: added hwraid gpg key
   apt_key: data="{{ lookup('file', 'hwraid_repo.key') }}" state=present
   when: ansible_hostname is match('mebibyte')

 - name: added hwraid repo for LSI raid controller
   apt_repository: repo="deb http://hwraid.le-vert.net/debian bullseye main" state=present
   when: ansible_hostname is match('mebibyte')
