---
- name: deploy systemd-resolved config
  template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: 0644
  register: resolved_conf

- name: enable and start resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: true
  when: resolved_conf.changed

- name: make resolv.conf a symlink to /lib/systemd/resolv.conf
  file:
    path: /etc/resolv.conf
    state: link
    src: /lib/systemd/resolv.conf
    force: yes