---
  # Setting vim as default editor
  - name: vim is our editor
    alternatives: name=editor path=/usr/bin/vim.basic

  - name: replace root vimrc
    copy:
      src: user/default/vimrc
      dest: /root/.vimrc

  # Adding content to files
  - name: enable syntax highlighting in vim
    lineinfile: dest=/etc/vim/vimrc regexp="^syntax "
                line="syntax on"

  - name: enable dark background in vim
    lineinfile: dest=/etc/vim/vimrc state=present regexp="^set background"
                line="set background=dark"

  - name: disable mouse support in vim
    lineinfile: dest=/etc/vim/vimrc state=present regexp="^autocmd BufEnter \* set mouse=$"
                line="autocmd BufEnter * set mouse=" backrefs=yes
