---
  - include: ../../../handlers/nginx.yml
  - include: ../../../handlers/systemd.yml
  - include: ../../../handlers/rc_local.yml
  - include: ../../../handlers/sysctl.yml
  - name: reload consul-template
    service:
      name: consul-template
      state: reloaded
