---
  - include: ../../../handlers/nginx.yml
  - include: ../../../handlers/systemd.yml
  - include: ../../../handlers/rc_local.yml
  - include: ../../../handlers/sysctl.yml
  - include: ../../../roles/letsencrypt/handlers/main.yml domain={{ ansible_fqdn }}
