### Master-Relay variables
# - host stream-info api
# - do fanout
# - distribute local files via nginx
# - setup icedist for accepting streams
stream_master: no

# should be exclusive to stream_master
stream_edge: no

# Generate relive snippets locally
relive_master: no

# default cache sizes
nginx_hls_relive_cache_max_size: '30g'
nginx_live_cache_max_size: '30g'
nginx_media_static_cache_max_size: '20g'

# backends
nginx_media_static_masters: []

# fanout to youtube
youtube: no
