---
- file: path=/etc/nginx/sites-enabled/default state=absent
- file: path=/etc/nginx/sites-enabled/00-acmetool.conf state=absent

- name: create endpoints in nginx config
  template: src=nginx/node.cdn.media.ccc.de
        dest=/etc/nginx/sites-available/node.cdn.media.ccc.de
        owner=root group=root mode=0640
  notify:
    - reload nginx

- name: enable endpoints in nginx config
  file: src=/etc/nginx/sites-available/node.cdn.media.ccc.de
        dest=/etc/nginx/sites-enabled/node.cdn.media.ccc.de
        state=link
  notify:
    - reload nginx

- name: ensure nginx is enabled and running
  systemd:
    name: nginx
    enabled: true
    state: started
