---
- file: path=/srv/www state=directory owner=www-data group=www-data
- template: src=sync-cdn.sh
        dest=/usr/local/bin/sync-cdn.sh
        owner=root group=root mode=0755

- template: src=sync-webroot.sh
        dest=/usr/local/bin
        owner=root group=root mode=0755

- cron: user=ftp minute="*/15" cron_file="local_mirror"
        job="if [ -x /usr/local/bin/sync-cdn.sh ]; then /usr/local/bin/sync-cdn.sh; fi;"
        name="sync cdn files"

- cron: user=www-data minute="*/3" cron_file="local_mirror"
        job="if [ -x /usr/local/bin/sync-webroot.sh ]; then /usr/local/bin/sync-webroot.sh; fi;"
        name="sync webroot"
