---
  - apt:
      state: latest
      name:
        - vsftpd
        - lockfile-progs
  - import_tasks: cdn-sync.yml
  # TODO add rsyncd configuration
  #   mirrorbits checks via rsync, config is done in media-cdn role,
  #   extract to rsyncd server role someday so it can be included here for mirrors (?)
