- name: create /etc/consul-template.d/ directory
  file:
    path: /etc/consul-template.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy consul-template service
  template:
    src: systemd-units/consul-template.service.j2
    dest: /etc/systemd/system/consul-template.service
  register: consul_template_service

- name: Enable consul-template service
  systemd:
    name: consul-template
    enabled: yes
    daemon_reload: yes
    state: "restarted"
  when: consul_template_service.changed

- name: Remove old nginx config
  file:
    path: /etc/nginx/sites-available/relay.conf
    state: absent

- name: Remove old nginx config2
  file:
    path: /etc/nginx/relay.conf
    state: absent

- name: Deploy consul-template nginx config
  template:
    src: nginx/relay-consul.ctmpl.j2
    dest: /etc/consul-template.d/relay.ctmpl
  notify: reload consul-template