---
  - name: create rc.local
    template:
      src: rc.local/rc.local.j2
      dest: /etc/rc.local
      mode: 0755
    register: rc_local

  - name: reload rc.local
    command: /etc/rc.local
    when: rc_local.changed