---
  - include: ../../../register/bin_path.yml

  - include: upload.yml
    tags: [nginx, upload, stream_master]
    when: stream_master|bool

  - include: nginx.yml
    tags: nginx

  - include: iptables.yml
    tags: iptables

  - include: sysctl.yml
    tags: sysctl

  - include: collectd.yml
    tags: [collectd, monitoring]

  - include: relive.yml
    when: relive_master|bool
    tags: relive

  - include: fanout.yml
    when: stream_master|bool
    tags: fanout

  - include: stream_master.yml
    when: stream_master|bool
    tags: [stream_master, stream_api]

  - include: register_relay.yml
    tags: register_relay
