---
  # Create stream_master htpasswd
  - name: install additional dependencies
    apt:
      package: python3-passlib
      state: latest
    when: stream_master|bool
    tags: stream_master

  - name: create stream_master htpasswd
    htpasswd:
      path: /etc/nginx/htpasswd
      name: "{{ stream_api.user }}"
      password: "{{ stream_api.password }}"
      owner: root
      group: www-data
      mode: 0640
    when: stream_master|bool
    tags: stream_master

  # Create directories
  - name: added nginx htdocs and caching directories
    file: "dest=/srv/nginx/{{ item }}
          owner=www-data group=www-data
          state=directory mode=0750"
    with_items:
      - "cache/tmp"
      - "cache/hls_relive"
      - "cache/live"

  # Manage vhost
  - name: create relay vhost
    template: dest="/etc/nginx/sites-available/{{ item }}"
              src="nginx/{{ item }}.j2"
              mode=0640 owner=root group=root
    with_items:
      - relay.conf
    register: relay_vhost

  - name: enable relay vhost
    file: src=/etc/nginx/sites-available/relay.conf
          dest=/etc/nginx/sites-enabled/relay.conf
          state=link
    register: relay_vhost_link

  - name: reload nginx
    service:
      name: nginx
      state: reloaded
    when: relay_vhost.changed or relay_vhost_link.changed