---
  # Create stream_master htpasswd
  - name: install additional dependencies
    apt:
      package: python3-passlib
      state: latest
    when: stream_master|bool
    tags: stream_master

  - name: create stream_master htpasswd
    htpasswd:
      path: /etc/nginx/htpasswd
      name: "{{ stream_api.user }}"
      password: "{{ stream_api.password }}"
      owner: root
      group: www-data
      mode: 0640
    when: stream_master|bool
    tags: stream_master

  # Create directories
  - name: added nginx htdocs and caching directories
    file: "dest=/srv/nginx/{{ item }}
          owner=www-data group=www-data
          state=directory mode=0750"
    with_items:
      - "cache/tmp"
      - "cache/hls_relive"
      - "cache/live"

  - name: "Register consul service"
    template:
      src: nginx/relay.hcl
      dest: /etc/consul.d/nginx.hcl
    notify: reload consul
    tags: [consul, consul-template]