---
  - name: make sure ruby is installed
    apt:
      name: ruby
      state: latest

  - name: install register_relay client
    template:
      src: register_relay/client.rb
      dest: /usr/local/sbin/register_relay
      mode: 0750
    register: register_relay_client

  - name: add register_relay systemd unit
    template:
      src: register_relay/register_relay.service.j2
      dest: /etc/systemd/system/register_relay.service
    register: register_relay_unit

  - name: trigger and enable register_relay
    service:
      name: register_relay
      state: restarted
      daemon_reload: yes
      enabled: yes
    when: register_relay_client.changed or register_relay_unit.changed

  - name: install register bandwith measure client
    template: dest=/usr/local/sbin/register_bw_measure
              src=measure_bw/client.rb
              mode=0750 owner=root group=root
