---
  - name: template telegraf config
    template:
      src: telegraf/telegraf.conf
      dest: /etc/telegraf/
      group: telegraf
      mode: 0640
    register: telegraf_config

  - name: copy dns script
    copy: src=dns-stats.py dest=/opt/dns-stats.py mode=0755
    when: monitoring_role is defined and monitoring_role == "dns"

  - name: reload telegraf
    service:
      name: telegraf
      state: reloaded
    when: telegraf_config.changed
