---
  - include: php.yml
    tags: php
    when: php|bool

  - include: nginx.yml

  - include: nginx_rtmp.yml
    tags: rtmp
    when: rtmp|bool

  - include: remove_nginx_rtmp.yml
    tags: rtmp
    when: not rtmp|bool

  - include: rtmp_auth.yml
    when: rtmp|bool and rtmp_auth is defined and rtmp_auth|bool
    tags: rtmp

  - include: monitoring.yml
    tags: monitoring
    when: not no_monitoring|bool

