---
  # Install packages
  - name: install nginx package
    apt:
      name: nginx
      state: latest
    tags: install

  # Configure
  - name: deploy nginx config
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0640
    register: nginx_conf

  # Manage vhost
  - name: remove default vhost
    file:
      dest: /etc/nginx/sites-enabled/default
      state: absent
    register: nginx_vhost

  # Letsencrypt hooks/reloads
  - name: undeploy ocsp reload
    cron:
      name: "reload nginx for ocsp update"
      user: root
      state: absent

  - name: remove letsencrypt hooks
    file:
      path: /etc/letsencrypt/renewal-hooks/post/20-nginx
      state: absent

  - name: make sure letsencrypt hookdir is present
    file:
      dest: /etc/dehydrated/hook.d
      state: directory
      mode: 0750

  - name: deploy letsencrypt hook
    template:
      src: letsencrypt-hook.sh
      dest: /etc/dehydrated/hook.d/20-nginx.sh
      mode: 0750

  # Enable/Disable service
  - name: enable/start nginx
    service:
      name: nginx
      enabled: yes
      state: started
    when: (nginx is defined and nginx|bool)

  - name: reload nginx
    service:
      name: nginx
      state: reloaded
    when: (nginx is defined and nginx|bool) and (nginx_conf.changed or nginx_vhost.changed)

  - name: disable/stop nginx
    service:
      name: nginx
      enabled: no
      state: stopped
    when: not (nginx is defined and nginx|bool)