---
- name: install nginx-rtmp module
  apt:
    name: "libnginx-{{ nginx_rtmp_mod }}"
    state: latest
  register: nginx_rtmp_module

- name: create nginx-rtmp config directory
  file:
    path: /etc/nginx-rtmp
    state: directory

- name: create nginx-rtmp config
  template:
    dest: /etc/nginx-rtmp/nginx.conf
    src: nginx-rtmp.conf.j2
    mode: 0640
    owner: root
    group: root
  register: nginx_rtmp_config

- name: install nginx-rtmp service
  copy:
    src: nginx-rtmp.service
    dest: /etc/systemd/system/nginx-rtmp.service
  register: nginx_rtmp_service

- name: restart/enable nginx-rtmp service
  systemd:
    name: nginx-rtmp
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: nginx_rtmp_module.changed or nginx_rtmp_config.changed or nginx_rtmp_service.changed

