---
- name: remove nginx-rtmp config
  file:
    path: /etc/nginx-rtmp/nginx.conf
    state: absent
  register: nginx_rtmp_conf

- name: stop and disable nginx-rtmp service
  systemd:
    name: nginx-rtmp
    state: stopped
    enabled: no
    daemon_reload: yes
  when: nginx_rtmp_conf.changed

- name: remove nginx-rtmp service
  file:
    path: /etc/systemd/system/nginx-rtmp.service
    state: absent

