---
  - name: restart nginx
    systemd:
      name: nginx.service
      state: restarted

  - name: reload nftables
    systemd:
      name: nftables.service
      enabled: yes
      state: restarted
