# runs proxmox
dummy = true

# Needs user 'root' for apply.
# Please install packages 'sudo', 'jq' and 'mosquitto-clients' manually.
bundles = ["mqtt-monitoring", "systemd", "systemd-timers"]

[metadata.mqtt-monitoring]
plugins = ["zfs_status"]
