groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder4"
token.meta = "!kee_user:ansible|worker-groups|encoder4-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder4"
secret.meta = "!kee_pass:ansible|worker-groups|encoder4-meta"

[metadata.interfaces.eth0]
ips = ["10.73.4.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 5
mode = "1080p25"
hdmi = true

[metadata.voctocore.audio.original]
streams = "0"
input = "cam1"

[metadata.voctocore.audio.translated]
streams = "1"
input = "cam1"
