groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder4"
token.meta = "!kee_user:ansible|worker-groups|encoder4-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder4"
secret.meta = "!kee_pass:ansible|worker-groups|encoder4-meta"

[metadata.event]
room_name = "Hörsaal 4, Demosession (0313)"

[metadata.interfaces.eth0]
ips = ["10.73.4.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.cam2]
devicenumber = 4
mode = "1080i50"
scan = "interlaced"
hdmi = true

[metadata.voctocore.sources.slides]
devicenumber = 5
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
