groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder3"
token.meta = "!kee_user:ansible|worker-groups|encoder3-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder3"
secret.meta = "!kee_pass:ansible|worker-groups|encoder3-meta"

autostart_scripts = [ "recording-scheduler", "mount4cut", "cut-postprocessor", "postencoding", "postprocessing" ]

[metadata.event]
room_name = "Einstein-Saal"

[metadata.interfaces.eth0]
ips = ["10.73.3.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
mirror_view = true

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080i50"

[metadata.voctocore.sources.cam2]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 5
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
