groups = ["debian-bullseye"]

[metadata]
do_not_import_default_users = true

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoderc4"
token.meta = "!kee_user:ansible|worker-groups|encoderc4-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoderc4"
secret.meta = "!kee_pass:ansible|worker-groups|encoderc4-meta"

[metadata.event]
name = "OpenChaos"
room_name = "C4"
room_number = 97
slug = "oc"

[metadata.interfaces.enp0s31f6]
ips = ["172.23.23.5/23", "10.73.97.3/24"]
gateway4 = "172.23.23.1"

[metadata.firewall.port_rules]
"*" = ["rfc1918"]
"*/udp" = ["rfc1918"]

[metadata.users.florob]
[metadata.users.florolf]
[metadata.users.ike]
[metadata.users.lukas2511]
[metadata.users.qb]
[metadata.users.y0sh]

[metadata.voctocore]
# because we're using voctomix2 main branch
custom_voctocore_config = true
streaming_endpoint = "s97"

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 0
mode = "1080p60"
hdmi = true

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"

[metadata.voctomix2]
# because voctomix2 branch is not yet compatible with bullseye as of 2022-09-25
rev = "main"
