groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder1"
token.meta = "!kee_user:ansible|worker-groups|encoder1-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder1"
secret.meta = "!kee_pass:ansible|worker-groups|encoder1-meta"

[metadata.event]
room_name = "K2 Rahel Liebeschütz-Plaut"

[metadata.interfaces.eth0]
ips = ["10.73.1.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
mirror_view = true

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.cam2]
devicenumber = 0
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 2
mode = "1080p50"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam2"
