groups = ["debian-buster", "mixers"]

[metadata.event]
room_name = "Audimax 1"

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder-hacc"
token.meta = "!kee_user:ansible|worker-groups|encoder-hacc-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder-hacc"
secret.meta = "!kee_pass:ansible|worker-groups|encoder-hacc-meta"

[metadata.interfaces.eth0]
ips = ["10.73.81.3/16"]
gateway4 = "10.73.0.254"

[metadata.interfaces.eth1]
dhcp = true

[metadata.voctogui]
high_dpi = true

[metadata.voctocore]
streaming_endpoint = "!kee_pass:ansible|stream-api|encoders|hacc"
srt_publish = true

[metadata.voctocore.sources.cam1]
devicenumber = "4"
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = "3"
mode = "1080p60"
hdmi = true

[metadata.voctocore.audio.original]
streams = "0+1"
input = "slides"
