groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder6"
token.meta = "!kee_user:ansible|worker-groups|encoder6-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder6"
secret.meta = "!kee_pass:ansible|worker-groups|encoder6-meta"

[metadata.event]
room_name = "DOUGLASIE (Mathegebäude, V)"

[metadata.interfaces.eth0]
ips = ["10.73.6.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 3
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
