groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder191"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder191"

[metadata.event]
room_name = "Saal 191"

[metadata.interfaces.eth0]
ips = ["10.73.191.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 2
mode = "1080p25"

[metadata.voctocore.sources.cam2]
devicenumber = 3
mode = "1080p25"

[metadata.voctocore.sources.cam3]
devicenumber = 4
mode = "1080p50"

[metadata.voctocore.sources.slides]
devicenumber = 5
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
