hostname = "10.73.7.3"
groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "nope"
secret.encoding = "nope"

[metadata.event]
room_name = "GLT23"

[metadata.interfaces.eth0]
ips = [
    "192.168.28.24/24",
    "10.73.7.3/16",
]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_endpoint = "s7"
streaming_auth_key = "!decrypt:encrypt$gAAAAABkOSLVPvOwcn_e-rKhrlW6PIT0-z09xbzbboQh37snWqJ6gGfEwnv5SNuFYL1m7LXEig4_l8-EtYAgrH2wc2p3egUd5LNCgHTmZfdf60z22P7BQvU="

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.sources.cam2]
devicenumber = 1
mode = "1080p30"

[metadata.voctocore.sources.slides]
devicenumber = 2
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
