groups = ["debian-buster"]

[metadata.event]
room_name = "Audimax 1"

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|encoder5"
token.meta = "!kee_user:ansible|worker-groups|encoder5-meta"
secret.encoding = "!kee_pass:ansible|worker-groups|encoder5"
secret.meta = "!kee_pass:ansible|worker-groups|encoder5-meta"

[metadata.interfaces.eth0]
ips = ["10.73.5.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080i50"

[metadata.voctocore.sources.cam2]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 3
mode = "1080p30"

[metadata.voctocore.audio.original]
streams = "0+0"
input = "cam1"

[metadata.voctocore.audio.translation1]
streams = "1+1"
input = "cam1"

[metadata.voctocore.audio.translation2]
streams = "0+0"
input = "cam2"

[metadata.voctocore.audio.translation3]
streams = "1+1"
input = "cam2"
