hostname = "10.73.3.3"
groups = ["debian-buster"]

[metadata.interfaces.eth0]
ips = ["10.73.3.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.cam2]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 4
mode = "1080p25"
hdmi = true

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
