groups = ["debian-buster"]

[metadata.crs-worker.secrets]
encoding.secret = "!kee_pass:ansible|worker-groups|encoder6"
encoding.token = "!kee_user:ansible|worker-groups|encoder6"
meta.secret = "!kee_pass:ansible|worker-groups|encoder6-meta"
meta.token = "!kee_user:ansible|worker-groups|encoder6-meta"

[metadata.event]
room_name = "C3VOC.tv"

[metadata.interfaces.eth0]
ips = ["10.73.6.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkNYk0lzAoL1Hf5xuaCK0E6A9xq15GeqVfsTCHDomSz0RcFz-kzlyQaS6wXWTsEPF21QhvncKBIstse1UP1Ue5fOKP1J9ruv5ScZrnfctymdDCpuc="

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080p50"

[metadata.voctocore.sources.cam2]
devicenumber = 2
mode = "1080p50"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
