hostname= "loudness.voc.fslab.de"
groups = ["debian-bullseye"]
bundles = ["loudness-rendering", "mqtt-monitoring"]

[metadata]
hostname = "loudness.voc.fslab.de"

[metadata.interfaces.ens18]
ips = ["10.73.128.160/16"]
gateway4 = "10.73.128.201"

[metadata.loudness-rendering]
s1 = "https://cdn.c3voc.de/hls/s1/native_hd.m3u8"
s2 = "https://cdn.c3voc.de/hls/s2/native_hd.m3u8"
s3 = "https://cdn.c3voc.de/hls/s3/native_hd.m3u8"
s4 = "https://cdn.c3voc.de/hls/s4/native_hd.m3u8"
s5 = "https://cdn.c3voc.de/hls/s5/native_hd.m3u8"
s6 = "https://cdn.c3voc.de/hls/s6/native_hd.m3u8"
