hostname= "10.73.170.4"
#hostname= "loudness-rendering.lan.c3voc.de"
groups = ["debian-bullseye"]
bundles = ["loudness-rendering"]

[metadata.interfaces.ens18]
ips = ["10.73.200.98/16"]

[metadata.loudness-rendering]
s1 = "https://cdn.c3voc.de/hls/s1/native_hd.m3u8"
s2 = "https://cdn.c3voc.de/hls/s2/native_hd.m3u8"
s3 = "https://cdn.c3voc.de/hls/s3/native_hd.m3u8"
s4 = "https://cdn.c3voc.de/hls/s4/native_hd.m3u8"
#s5 = "https://cdn.c3voc.de/hls/s2/native_hd.m3u8"
#s6 = "https://cdn.c3voc.de/hls/s2/native_hd.m3u8"
