hostname = "10.73.7.7"
groups = ["debian-bullseye"]

[metadata.crs-worker]
token.encoding = "!decrypt:encrypt$gAAAAABkOS_Us1SxDDO0JZGgPQ7g-VMCw792NVYP2-k8wY5okEnlD_OWTePmEIbF6RK0h2tHZ9bRV_ReRPRLH3GPIsDA_49YaRQYoxzTQUkFOkEin9LQDiGsyAFfMtS5bP42Sfc3k8DT"
secret.encoding = "!decrypt:encrypt$gAAAAABkOS_by1-OF4v0BuFqOwofXy4ka7cp5v7UQjxjrvQasQbmx4p4W4ZYPu0GyZwWvIzJdR0gUymexb-2QrzJAMD1fZd3p3BZQmHOlFulwegjXZIyKYo3SsgTnt9NsnSzYqNBNclY"

[metadata.grub.cmdline_linux]
'net.ifnames' = '1'

[metadata.interfaces.enp35s0]
ips = ["10.73.7.7/16"]
gateway4 = "10.73.0.254"
