groups = ["debian-buster"]

[metadata.crs-worker.secrets.encoding]
token = "!kee_user:ansible|worker-groups|minion6"
secret = "!kee_pass:ansible|worker-groups|minion6"

[metadata.interfaces.eth0]
ips = ["10.73.6.7/16"]
gateway4 = "10.73.0.254"
