groups = ["debian-bullseye"]
hostname = "minion128-3.voc.fslab.de"

[metadata]
hostname = "minion128-3.voc.fslab.de"

[metadata.interfaces.ens18]
ips = ["10.73.128.152/16"]
gateway4 = "10.73.128.201"
