bundles = ["pygtk-atem-switcher"]
groups = ["debian-bullseye"]

[metadata.apt.firmware-amd-graphics]
[metadata.apt.firmware-linux-nonfree]
[metadata.apt.mesa-utils]

[metadata.mixer-common]
enable-irssi = false

[metadata.voctogui]
high_dpi = false

[metadata.interfaces.eth0]
ips = ["10.73.191.1/16"]
gateway4 = "10.73.0.254"
