bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-buster"]

[metadata.interfaces.eth0]
ips = ["10.73.1.1/16"]
gateway4 = "10.73.0.254"

[metadata.pygtk-atem-switcher.atem.settings.inputs]
input1 = "Laptop"
input2 = "steffen"
input3 = "x"
input4 = "info-beamer"
