hostname = "10.73.7.1"
groups = ["debian-buster"]

[metadata.interfaces.eth0]
ips = [
    "192.168.28.22/24",
    "10.73.7.1/16",
]
gateway4 = "10.73.0.254"

[metadata.voctogui]
encoder-ip = "10.73.7.3"
high_dpi = false
