bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-buster"]

[metadata.interfaces.eth0]
ips = ["10.73.5.1/16"]
gateway4 = "10.73.0.254"

[metadata.pygtk-atem-switcher.atem.settings.inputs]
input1 = "info-beamer"
input2 = "x"
input3 = "DocCam"
input4 = "laptop"
