hostname = "10.8.170.1"
bundles = [
    "isc-dhcp-server",
    "netdata",
    "openvpn-client",
]
groups = ["debian-bullseye"]

[metadata.interfaces.ens18]
#dhcp = true
ips = ["141.23.55.14/24"]
gateway4 = "141.23.55.1"

[metadata.interfaces.ens19]
ips = [
    "10.73.0.254/16",
    "10.73.200.201/16",
    "10.8.170.1/24"
]

[metadata.isc-dhcp-server.subnets.ens19]
range_lower = "10.8.170.2"
range_higher = "10.8.170.254"
subnet = "10.8.170.0/24"
options.broadcast-address = "10.8.170.255"
options.domain-name-servers = "9.9.9.10, 149.112.112.10"
options.domain-search = "lan.c3voc.de"
options.routers = "10.8.170.1"
options.subnet-mask = "255.255.255.0"

[metadata.nftables.rules]
"50-router" = [
    "inet filter forward ct state { related, established } accept",
    "inet filter forward iifname { ens19, tun0 } accept",
    "inet filter forward tcp dport 22 accept",
    "nat postrouting oifname ens18 masquerade",

    "nat prerouting ip daddr 141.23.55.14 tcp dport 22 dnat to 10.73.0.2",

    # XXX migration from old vm to new router vm, remove this once
    # everything in the server case has been redeployed
    "nat prerouting iifname ens19 tcp dport 53 dnat to 9.9.9.10",
    "nat prerouting iifname ens19 udp dport 53 dnat to 9.9.9.10",
]

[metadata.sysctl.options]
"net.ipv4.ip_forward" = "1"
