hostname = "10.73.200.201"
bundles = [
    "isc-dhcp-server",
    "netdata",
    "openvpn-client",
    "radvd",
    "unbound-with-knot",
]
groups = ["debian-bullseye"]

[metadata.interfaces.ens18]
ips = [
    "94.45.241.105/24",
    "2001:67c:20a1:2241::105/64",
]
gateway4 = "94.45.241.1"

[metadata.interfaces.ens19]
ips = [
    "10.73.0.254/16",
    "10.73.200.201/16",
    "2001:67c:20a1:3504:10:73:200:201/64",
]

[metadata.isc-dhcp-server.subnets.ens19]
range_lower = "10.73.170.1"
range_higher = "10.73.170.254"
subnet = "10.73.0.0/16"
options.broadcast-address = "10.73.255.255"
options.domain-name-servers = "10.73.0.254"
options.domain-search = "lan.c3voc.de"
options.routers = "10.73.0.254"
options.subnet-mask = "255.255.0.0"

[metadata.nftables.rules]
"50-router" = [
    "inet filter forward ct state { related, established } accept",
    "inet filter forward iifname { ens19, tun-voc } accept",
    "nat postrouting oifname ens18 masquerade",
]

[metadata.radvd.interfaces.ens19]
prefix = "2001:67c:20a1:3504::/64"
rdnss = ["2001:67c:20a1:3504:10:73:200:201"]

[metadata.sysctl.options]
"net.ipv4.ip_forward" = "1"
"net.ipv6.conf.all.forwarding" = "1"

[metadata.unbound-with-knot]
threads = 4
cache_slabs = 4
primary = "!kee_user:ansible|router|knot secret"
primary_secret = "!kee_pass:ansible|router|knot secret"
