hostname = "10.73.7.100"
bundles = [
    "encoder-common",
    "samba",
    "zfs",
]
groups = [
    "crs-workers",
    "debian-bullseye",
    "saal-glt",
]

[metadata.crs-worker]
autostart_scripts = [ "recording-scheduler", "mount4cut", "cut-postprocessor", "postencoding", "postprocessing" ]
token.encoding = "!decrypt:encrypt$gAAAAABkOS_Us1SxDDO0JZGgPQ7g-VMCw792NVYP2-k8wY5okEnlD_OWTePmEIbF6RK0h2tHZ9bRV_ReRPRLH3GPIsDA_49YaRQYoxzTQUkFOkEin9LQDiGsyAFfMtS5bP42Sfc3k8DT"
secret.encoding = "!decrypt:encrypt$gAAAAABkOS_by1-OF4v0BuFqOwofXy4ka7cp5v7UQjxjrvQasQbmx4p4W4ZYPu0GyZwWvIzJdR0gUymexb-2QrzJAMD1fZd3p3BZQmHOlFulwegjXZIyKYo3SsgTnt9NsnSzYqNBNclY"

[metadata.grub.cmdline_linux]
'net.ifnames' = '1'

[metadata.interfaces.eno1]
ips = [
    "10.73.7.100/16",
    "10.73.0.254/16",
]

[metadata.interfaces.eno2]
ips = [
    "10.87.73.100/16",
]
gateway4 = "10.87.0.1"

[metadata.nftables.rules]
"50-router" = [
    "inet filter forward ct state { related, established } accept",
    "inet filter forward iifname eno1 accept",
    "nat postrouting oifname eno2 masquerade",

    # "dns"
    "nat prerouting tcp dport 53 dnat to 8.8.8.8",
    "nat prerouting udp dport 53 dnat to 8.8.8.8",
    "inet filter input iifname eno1 tcp dport 53 accept",
    "inet filter input iifname eno1 udp dport 53 accept",
]

[metadata.sysctl.options]
"net.ipv4.ip_forward" = "1"

[metadata.zfs.pools.video.when_creating]
ashift = 12

[[metadata.zfs.pools.video.when_creating.config]]
devices = [
    "/dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N1_WD-WX92DA1LZA99",
]
