bundles = [
    "encoder-common",
    "mqtt-monitoring",
    "sysconfig",
    "systemd",
    "systemd-timers",
    "users",
]
groups = ["crs-workers"]

[metadata.crs-worker]
autostart_scripts = [ "recording-scheduler", "mount4cut", "cut-postprocessor", "postencoding", "postprocessing" ]
token.encoding = "!kee_user:ansible|worker-groups|storage"
secret.encoding = "!kee_pass:ansible|worker-groups|storage"

[metadata.event]
slug = "t4at2022"
