---
  # copy image assets to each host in media-cdn group (static.media.ccc.de)
  # - hosts: media-asset-src
  #   roles:
  #     - role: media-assets
  #       gather_facts: no
  #       tags: ['media-assets']

  # media cdn master (cdn.media.ccc.de)
  - hosts: media-cdn
    roles:
      - { role: common, tags: ['common'] }
      - { role: monitoring-client, vars: { 'monitoring_role': 'media-cdn' }, tags: ['monitoring'] }
      - { role: nginx, vars: { 'anonymize_logs': true }, tags: ['nginx'] }
      - { role: letsencrypt, tags: ['letsencrypt'], vars: {'use_lednsapi': true} }
      - { role: media-cdn-node, tags: ['cdn-node'] }
      - { role: media-cdn, tags: ['media-cdn'] }
