---
  - hosts: media-mirror
    roles:
      - { role: common, tags: ['common'] }
      - { role: monitoring-client, vars: { 'monitoring_role': 'media-mirror' }, tags: ['monitoring'] }
      - { role: nginx, vars: { 'anonymize_logs': true }, tags: ['nginx'] }
      - { role: letsencrypt, tags: ['letsencrypt'], vars: {'use_lednsapi': true} }
      - { role: media-cdn-node, tags: ['cdn-node'] }
      - { role: media-mirror, tags: ['media-mirror'] }
