---
  - name: install collectd config file
    template:
      src: collectd/collectd.server.conf.j2
      dest: /etc/collectd/collectd.conf
      mode: 0640
    register: collectd_config

  - name: install collectd auth file
    template:
      src: collectd/passwd.j2
      dest: /etc/collectd/passwd
      mode: 0600

  - name: restart collectd
    service:
      name: collectd
      state: restarted
    when: collectd_config.changed