---
  - name: install grafana config file
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
      group: grafana
      mode: 0640
    register: grafana_config

  - name: restart grafana
    service:
      name: grafana-server
      state: restarted
    when: grafana_config.changed