---
  - name: install carbon config file
    template: dest=/etc/carbon/carbon.conf
              src=graphite/carbon.conf.j2
              owner=root group=_graphite mode=0640
    notify: restart carbon-cache
    tags:
      - config

  - name: install carbon storage-schemas file
    template: dest=/etc/carbon/storage-schemas.conf
              src=graphite/storage-schemas.conf.j2
              owner=root group=_graphite mode=0640
    tags:
      - config

  - name: install graphite-api config
    template: dest=/etc/graphite-api.yaml
              src=graphite/graphite-api.yaml.j2
              owner=root group=_graphite mode=0640
    # notify: restart graphite-api
    tags:
      - config