---
  - name: add influxdata apt key
    apt_key:
      id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
      url: https://repos.influxdata.com/influxdb.key
      state: present
    tags: apt

  - name: add influxdata repository
    apt_repository:
      repo: deb https://repos.influxdata.com/debian buster stable
      state: present
    tags: apt

  - name: install monitoring packages
    apt:
      name:
        - nagios-plugins-basic
        - grafana
        - prometheus
        - prometheus-alertmanager
        - prometheus-node-exporter
        - prometheus-blackbox-exporter
        - telegraf
      state: latest