---
# tracker vhosts
- name: "deploy tracker vhosts"
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    mode: 0640
  register: tracker_vhosts
  loop:
    - tracker.conf
    - default.conf

- name: "enable tracker vhosts"
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop:
    - tracker.conf
    - default.conf
  when: tracker_vhosts.changed

# tracker fastcgi_params
- name: deploy tracker spcific fastcgi_params
  template:
    src: nginx/fastcgi_params
    dest: /etc/nginx/fastcgi_params
    mode: 0640
  register: fastcgi_params

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: (nginx is defined and nginx|bool) and (tracker_vhosts.changed or fastcgi_params.changed)
