---
# Install PHP + stuff
- name: install tracker php packages
  apt:
    name:
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-apcu"
      - "php{{ php_version }}-xsl"
      - "php{{ php_version }}-xmlrpc"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-dev"
      - "php-xdiff"
      - "php-pear"
    state: latest

# Create default pool
- name: configure php-fpm
  template:
    src: php_fpm/www.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    mode: 0644
  register: fpm_config

# Change php.ini settings
- name: adapt php ini settings
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    # don't expose version
    - { regex: 'expose_php.*=.*', line: 'expose_php = Off' }
    # short open tag
    - { regex: 'short_open_tag.*=.*', line: 'short_open_tag = On'}
  register: php_ini

# Enable service
- name: (re)start php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    enabled: yes
    state: restarted
  when: fpm_config.changed or php_ini.changed